export const QUESTION_TYPES = {
    SET_USER: 'SET_USER',
    SET_LOADING: 'SET_LOADING',
    SET_QUESTIONS: 'SET_QUESTIONS',
    SET_SUBJECT_SCORE: 'SET_SUBJECT_SCORE',
    BOOKMARK: 'BOOKMARK'
}

export const USER_TYPES = {
    SET_USER: "SET_USER"
}