export const QUESTION_TYPES = {
    SET_USER: 'SET_USER',
    SET_LOADING: 'SET_LOADING',
    SET_QUESTIONS: 'SET_QUESTIONS',
    SET_SUBJECT_SCORE: 'SET_SUBJECT_SCORE',
    SKIP: 'SKIP',
    RESET_SKIP: 'RESET_SKIP',
    SET_QUIZES: 'SET_QUIZES',
    SET_TEACHER_QUIZES: 'SET_TEACHER_QUIZES'
}

export const USER_TYPES = {
    SET_USER: "SET_USER",
    LOADING: "LOADING",
    SET_TOKEN: "SET_TOKEN",
    SET_TYPE: "SET_TYPE"
}